#!/bin/bash

set -e

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

git_resource_dir=$(cd $(dirname $0)/.. && pwd)
go_module_dir=$(cd $(dirname $0)/../hgresource && pwd)

if not_installed docker; then
  echo "# docker is not installed! run the following commands:"
  echo "    brew install docker"
  echo "    brew cask install docker-machine"
  echo "    docker-machine create dev --driver virtualbox"
  echo '    eval $(docker-machine env dev)'
  echo "    docker login"
  exit 1
fi

cd $go_module_dir
GOOS=linux go build

cd $git_resource_dir
docker build --rm .
